engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "src/*.js"
  - "feature-worker.js"
exclude_paths:
- "jsap.js"
- "js-xtract/*"
- "templates/*"
